- hosts: aws
  tasks:
    - name: Install httpd server
      package:
        name: "httpd"
        state: present

    - name: Copy Web pages   
      copy:
        dest: "/var/www/html"
        src: "/var/lib/jenkins/workspace/Web_Project/index.html"

    - name: Start server
      service:
        name: "httpd"
        state: started
        enabled: yes


